# presets/pure_serene_safe.py
"""风格预设: pure_serene_safe"""

PRESET = {
    "name": "pure_serene_safe",
    "description": "风格预设 - pure_serene_safe",
    "layers": {
        "subject": [
            "a beautiful young Asian woman, wearing a soft cream-colored knit sweater, sitting by a window looking at a bamboo forest, warm morning sunlight, cozy atmosphere, photorealistic fine art, framed artwork style",
            "a pure Chinese girl, elegant long-sleeved modern hanfu, walking through a misty bamboo forest with dappled sunlight, peaceful expression, serene beauty, landscape photography",
            "a serene Japanese maiden, wearing a simple traditional kimono with long sleeves, cherry blossom petals falling in a temple garden, soft pink light, gentle atmosphere",
            "a sweet Korean girl, wearing an oversized cream white sweater, holding a warm cup of coffee in a cozy cafe with soft warm lighting, natural makeup, peaceful expression",
            "a graceful Chinese girl, wearing a long elegant winter coat, holding an oil-paper umbrella, standing in a misty snowy ancient street, poetic atmosphere, timeless beauty",
            "a graceful European girl, blonde hair, wearing a thick white cable-knit sweater, standing in a lavender field under a golden hour sunset, innocent smile, dreamy fine art landscape",
            "a beautiful British woman, wearing a classic tweed coat, sitting in a rustic garden with morning mist, gentle expression, soft morning light, painted art style",
            "a romantic Italian girl, wearing a warm white scarf and long coat, standing on a balcony overlooking a sunset sea, Mediterranean breeze, peaceful and timeless beauty",
            "a gentle Nordic girl, wearing a simple heavy winter coat, standing in a snowy pine forest, soft cold winter light, crystal clear eyes, pure and elegant artistic portrait",
            "an ethereal Eastern European girl, wearing a long white winter coat, standing in a misty mountain meadow, soft mystical atmosphere, fairy-tale beauty",
            "a serene French girl, wearing a classic Breton striped shirt and white cardigan, sitting on a swing in a lush summer vineyard, warm golden afternoon light, vintage charm",
            "a pretty Greek girl, wearing a white linen shirt, standing by the blue Aegean sea, sea breeze, bright Mediterranean sunlight, radiant smile",
            "a charming Scottish girl, wearing a cozy tartan scarf, standing in a misty highlands moor, purple heather blooming, a sense of ancient and pure landscape",
            "a cute American girl, wearing a denim jacket and white shirt, sitting on a sunny wooden porch, golden hour light, relaxed smile, warm summer vibe",
            "an Australian girl, wearing a light beach cover-up, walking along a pristine beach at sunrise, ocean breeze, golden light, peaceful and free",
            "a graceful Canadian girl, wearing a cozy plaid sweater, sitting by a cabin window watching falling autumn leaves, comforting and serene",
            "a beautiful Hawaiian girl, wearing a floral sundress, standing under a palm tree at sunset, warm island breeze, relaxed and radiant",
            "a stunning Californian girl, wearing a white knitted sweater, leaning against a vintage van, soft desert sunset light, bohemian and free-spirited",
            "a beautiful Alaskan girl, wearing a thick white winter parka, standing in a snow-covered pine forest, faint aurora borealis in the night sky, mystical and pure",
            "a beautiful Brazilian girl, wearing a simple white linen cover-up, standing in a lush tropical rainforest, dappled sunlight through palm leaves, radiant and pure",
            "a charming Mexican girl, wearing a traditional embroidered white blouse, sitting in a sunny courtyard with blooming cacti and colorful flowers, soft smile, earthy warmth",
            "a young Argentine girl, wearing a light summer dress, standing in a golden pampas grass field, wind sweeping through her hair, soulful and gentle",
            "a graceful Colombian girl, wearing a flowing white dress, standing by a tranquil mountain lake in the Andes, crisp clean air, soft morning light",
            "a serene Middle Eastern girl, wearing a simple light beige abaya, standing at the edge of a desert oasis, soft golden sunset light, mysterious and elegant beauty",
            "a beautiful Ethiopian girl, wearing traditional white habesha kemis dress, sitting in a lush green highland meadow, soft morning mist, natural and pure",
            "a graceful Moroccan girl, wearing a simple white caftan, standing in a sunlit riad courtyard with orange trees, warm serene afternoon light, timeless beauty",
            "a gentle Egyptian girl, wearing flowing white cotton dress, standing near the ancient pyramids at twilight, soft warm breeze, mystical and serene",
            "a sweet South African girl, wearing a white sundress, standing in a blooming wildflower field near Cape Town, vibrant spring colors, fresh air, peaceful",
            "a charming Indian girl, wearing an elegant white saree, standing in a misty tea plantation in the mountains, early morning sunlight, serene and graceful",
            "a beautiful Thai girl, wearing a simple white traditional blouse, standing quietly in a serene tropical temple garden, soft warm sunlight, gentle smile",
        ],
        "scene": [
            "serene, peaceful, pure, elegant",
        ],
        "style": [
            "photorealistic cinematic portrait, natural lighting, blurred scenic background, soft warm color palette, art gallery aesthetic",
            "fine art photography, landscape background, long sleeves, modest fashion, masterpiece",
        ],
        "lighting": [
            "natural soft lighting",
            "diffused daylight",
            "studio soft light",
        ],
        "view": [
            "eye-level medium shot, balanced composition",
            "low angle shot, dramatic perspective",
            "bird's eye view, sweeping landscape",
            "close-up shot, shallow depth of field",
            "three-quarter view, elegant framing",
        ],
        "quality": [
            "8k, highly detailed, sharp focus, hyper-realistic textures",
            "4k, masterpiece, best quality, intricate fine details",
            "masterpiece, award-winning, stunning composition, vivid colors",
        ],
    },
}